/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: E:\zproject\zunzip\tools\fstar\bin\krml Closure.krml -tmpdir krml_out -no-prefix Closure
  F* version: <unknown>
  KaRaMeL version: 
 */

#include "internal/Closure.h"

#include "internal/Prims.h"

bool FStar_List_Tot_Base_mem__uint32_t(uint32_t x, Prims_list__uint32_t *uu___)
{
  if (uu___->tag == Prims_Nil)
    return false;
  else if (uu___->tag == Prims_Cons)
  {
    Prims_list__uint32_t *tl1 = uu___->tl;
    uint32_t hd1 = uu___->hd;
    if (hd1 == x)
      return true;
    else
      return FStar_List_Tot_Base_mem__uint32_t(x, tl1);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

Prims_list__uint32_t *insert(uint32_t x, Prims_list__uint32_t *l)
{
  if (FStar_List_Tot_Base_mem__uint32_t(x, l))
    return l;
  else
  {
    Prims_list__uint32_t *buf = KRML_HOST_MALLOC(sizeof (Prims_list__uint32_t));
    if (buf != NULL)
      buf[0U] = ((Prims_list__uint32_t){ .tag = Prims_Cons, .hd = x, .tl = l });
    return buf;
  }
}

Prims_list__uint32_t *union_acc(Prims_list__uint32_t *l, Prims_list__uint32_t *acc)
{
  if (l->tag == Prims_Nil)
    return acc;
  else if (l->tag == Prims_Cons)
  {
    Prims_list__uint32_t *q = l->tl;
    uint32_t x = l->hd;
    return union_acc(q, insert(x, acc));
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

Prims_list__uint32_t
*FStar_List_Tot_Base_append__uint32_t(Prims_list__uint32_t *x, Prims_list__uint32_t *y)
{
  if (x->tag == Prims_Nil)
    return y;
  else if (x->tag == Prims_Cons)
  {
    Prims_list__uint32_t *tl1 = x->tl;
    uint32_t a1 = x->hd;
    Prims_list__uint32_t *buf = KRML_HOST_MALLOC(sizeof (Prims_list__uint32_t));
    if (buf != NULL)
      buf[0U] =
        (
          (Prims_list__uint32_t){
            .tag = Prims_Cons,
            .hd = a1,
            .tl = FStar_List_Tot_Base_append__uint32_t(tl1, y)
          }
        );
    return buf;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

Prims_list__uint32_t
*FStar_List_Tot_Base_flatten__uint32_t(Prims_list__Prims_list__uint32_t *l)
{
  if (l->tag == Prims_Nil)
  {
    Prims_list__uint32_t *buf = KRML_HOST_MALLOC(sizeof (Prims_list__uint32_t));
    if (buf != NULL)
      buf[0U] = ((Prims_list__uint32_t){ .tag = Prims_Nil });
    return buf;
  }
  else if (l->tag == Prims_Cons)
  {
    Prims_list__Prims_list__uint32_t *tl1 = l->tl;
    Prims_list__uint32_t *hd1 = l->hd;
    return FStar_List_Tot_Base_append__uint32_t(hd1, FStar_List_Tot_Base_flatten__uint32_t(tl1));
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

Prims_list__Prims_list__uint32_t
*FStar_List_Tot_Base_map__uint32_t_Prims_list_uint32_t(
  Prims_list__uint32_t *(*f)(uint32_t x0),
  Prims_list__uint32_t *x
)
{
  if (x->tag == Prims_Nil)
  {
    Prims_list__Prims_list__uint32_t
    *buf = KRML_HOST_MALLOC(sizeof (Prims_list__Prims_list__uint32_t));
    if (buf != NULL)
      buf[0U] = ((Prims_list__Prims_list__uint32_t){ .tag = Prims_Nil });
    return buf;
  }
  else if (x->tag == Prims_Cons)
  {
    Prims_list__uint32_t *tl1 = x->tl;
    uint32_t a1 = x->hd;
    Prims_list__Prims_list__uint32_t
    *buf = KRML_HOST_MALLOC(sizeof (Prims_list__Prims_list__uint32_t));
    if (buf != NULL)
      buf[0U] =
        (
          (Prims_list__Prims_list__uint32_t){
            .tag = Prims_Cons,
            .hd = f(a1),
            .tl = FStar_List_Tot_Base_map__uint32_t_Prims_list_uint32_t(f, tl1)
          }
        );
    return buf;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

Prims_list__uint32_t
*step(Prims_list__uint32_t *(*edges)(uint32_t x0), Prims_list__uint32_t *frontier)
{
  return
    union_acc(FStar_List_Tot_Base_flatten__uint32_t(FStar_List_Tot_Base_map__uint32_t_Prims_list_uint32_t(edges,
          frontier)),
      frontier);
}

Prims_list__uint32_t
*closure(Prims_list__uint32_t *(*edges)(uint32_t x0), krml_checked_int_t fuel, uint32_t x)
{
  if (fuel == 0)
  {
    Prims_list__uint32_t *buf = KRML_HOST_MALLOC(sizeof (Prims_list__uint32_t));
    if (buf != NULL)
      buf[0U] = ((Prims_list__uint32_t){ .tag = Prims_Nil });
    Prims_list__uint32_t *buf0 = KRML_HOST_MALLOC(sizeof (Prims_list__uint32_t));
    if (buf0 != NULL)
      buf0[0U] = ((Prims_list__uint32_t){ .tag = Prims_Cons, .hd = x, .tl = buf });
    return buf0;
  }
  else
    return step(edges, closure(edges, Prims_op_Subtraction(fuel, 1), x));
}

bool
scan_back(
  Prims_list__uint32_t *(*edges)(uint32_t x0),
  krml_checked_int_t us,
  uint32_t x,
  Prims_list__uint32_t *l
)
{
  if (l->tag == Prims_Nil)
    return false;
  else if (l->tag == Prims_Cons)
  {
    Prims_list__uint32_t *q = l->tl;
    uint32_t y = l->hd;
    if (FStar_List_Tot_Base_mem__uint32_t(x, closure(edges, us, y)))
      return true;
    else
      return scan_back(edges, us, x, q);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

bool
self_cycle(
  Prims_list__uint32_t *(*edges)(uint32_t x0),
  krml_checked_int_t universe_size,
  uint32_t x
)
{
  return scan_back(edges, universe_size, x, edges(x));
}

