/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: E:\zproject\zunzip\tools\fstar\bin\krml Closure.krml -tmpdir krml_out -no-prefix Closure
  F* version: <unknown>
  KaRaMeL version: 
 */

#ifndef Closure_H
#define Closure_H

#include "krmllib.h"

typedef uint32_t node;

typedef struct Prims_list__uint32_t_s Prims_list__uint32_t;

#define Prims_Nil 0
#define Prims_Cons 1

typedef uint8_t Prims_list__uint32_t_tags;

typedef struct Prims_list__uint32_t_s
{
  Prims_list__uint32_t_tags tag;
  uint32_t hd;
  Prims_list__uint32_t *tl;
}
Prims_list__uint32_t;

Prims_list__uint32_t *insert(uint32_t x, Prims_list__uint32_t *l);

Prims_list__uint32_t *union_acc(Prims_list__uint32_t *l, Prims_list__uint32_t *acc);

Prims_list__uint32_t
*step(Prims_list__uint32_t *(*edges)(uint32_t x0), Prims_list__uint32_t *frontier);

Prims_list__uint32_t
*closure(Prims_list__uint32_t *(*edges)(uint32_t x0), krml_checked_int_t fuel, uint32_t x);

bool
scan_back(
  Prims_list__uint32_t *(*edges)(uint32_t x0),
  krml_checked_int_t us,
  uint32_t x,
  Prims_list__uint32_t *l
);

bool
self_cycle(
  Prims_list__uint32_t *(*edges)(uint32_t x0),
  krml_checked_int_t universe_size,
  uint32_t x
);


#define Closure_H_DEFINED
#endif /* Closure_H */
