/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: E:\zproject\zunzip\tools\fstar\bin\krml Closure.krml -tmpdir krml_out -no-prefix Closure
  F* version: <unknown>
  KaRaMeL version: 
 */

#ifndef internal_Closure_H
#define internal_Closure_H

#include "krmllib.h"

#include "../Closure.h"

bool FStar_List_Tot_Base_mem__uint32_t(uint32_t x, Prims_list__uint32_t *uu___);

Prims_list__uint32_t
*FStar_List_Tot_Base_append__uint32_t(Prims_list__uint32_t *x, Prims_list__uint32_t *y);

typedef struct Prims_list__Prims_list__uint32_t_s Prims_list__Prims_list__uint32_t;

typedef struct Prims_list__Prims_list__uint32_t_s
{
  Prims_list__uint32_t_tags tag;
  Prims_list__uint32_t *hd;
  Prims_list__Prims_list__uint32_t *tl;
}
Prims_list__Prims_list__uint32_t;

Prims_list__uint32_t
*FStar_List_Tot_Base_flatten__uint32_t(Prims_list__Prims_list__uint32_t *l);

Prims_list__Prims_list__uint32_t
*FStar_List_Tot_Base_map__uint32_t_Prims_list_uint32_t(
  Prims_list__uint32_t *(*f)(uint32_t x0),
  Prims_list__uint32_t *x
);


#define internal_Closure_H_DEFINED
#endif /* internal_Closure_H */
