/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: E:\zproject\zunzip\tools\fstar\bin\krml Closure.krml -tmpdir krml_out -no-prefix Closure
  F* version: <unknown>
  KaRaMeL version: 
 */

#ifndef internal_Prims_H
#define internal_Prims_H

#include "krmllib.h"

extern krml_checked_int_t Prims_op_Subtraction(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);


#define internal_Prims_H_DEFINED
#endif /* internal_Prims_H */
